osx_image: xcode10
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods 
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Pretty.xcworkspace -scheme Pretty-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' | xcpretty
- pod lib lint
